// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"hennge/yerassyl/twitterclone/internal/db"
	"hennge/yerassyl/twitterclone/internal/webservice"
)

// Injectors from wire.go:

func InitializeUserService() *webservice.UserService {
	pool := NewPool()
	userRepository := db.NewUserRepository(pool)
	userService := webservice.NewUserService(userRepository)
	return userService
}

func InitializerTweetService() *webservice.TweetService {
	pool := NewPool()
	tweetRepository := db.NewTweetRepository(pool)
	userRepository := db.NewUserRepository(pool)
	tweetService := webservice.NewTweetService(tweetRepository, userRepository)
	return tweetService
}
